cv/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

kao_pw/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from kao_pw import settings

urlpatterns = [
    path('', include('cv.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cv/models.py
from django.db import models


# Create your models here.
class Experience(models.Model):
    title = models.CharField(max_length=100)
    department = models.CharField(max_length=100, blank=True)
    position = models.CharField(max_length=50)
    description = models.TextField()
    start_date = models.DateField('start date')
    end_date = models.DateField('end date')


class Education(models.Model):
    university = models.CharField(max_length=100)
    country = models.CharField(max_length=20, default="")
    major = models.CharField(max_length=100)
    start_date = models.DateField('start date')
    end_date = models.DateField('end date')
    description = models.TextField(default="")


class Skill(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey('SkillCategory', on_delete=models.DO_NOTHING, null=True)
    level = models.IntegerField('level of skill range from 0 to 10', blank=True, null=True)

    def get_category(self):
        return self.category
        # return self.category.name

    def __str__(self):
        return self.name


class SkillCategory(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=9)
    collapse = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Framework(models.Model):
    name = models.CharField(max_length=100)
    skill = models.ForeignKey('Skill', on_delete=models.DO_NOTHING, null=True)
    show_skill = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.name

    def full_name(self):
        if self.show_skill:
            return "%s - %s" % (self.name, self.skill.name)
        return self.name


class Portfolio(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="portfolio/images")
    description = models.TextField()
    rank = models.IntegerField()
    link = models.TextField(default="")

    def __str__(self):
        return self.name


class Tag(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    framework = models.ForeignKey(Framework, on_delete=models.CASCADE)

    def __str__(self):
        return self.portfolio.name

cv/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import loader

from .models import Experience, Education, Skill, Portfolio


def index(request):
    experience_list = Experience.objects.order_by('-end_date')
    education_list = Education.objects.order_by('-end_date')
    skill_list = Skill.objects.all().order_by('category')
    portfolio_list = Portfolio.objects.all().order_by('rank')
    template = loader.get_template('cv/index.html')
    context = {
        'experience_list': experience_list,
        'education_list': education_list,
        'skill_list': skill_list,
        'portfolio_list': portfolio_list,
    }
    return HttpResponse(template.render(context, request))

cv/templates/cv/index.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-43724825-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-43724825-3');
    </script>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>Po-Wen Kao - Software Engineering</title>
	<meta name="description" content="Embedded Systems Engineer, Embedded System, Robotics, C++, C, Python, Java, Android, iOS, AR, Unity">
	<meta name="author" content="">

   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'cv/css/default.css'%}">
    <link rel="stylesheet" href="{% static 'cv/css/layout.css'%}">
    <link rel="stylesheet" href="{% static 'cv/css/media-queries.css'%}">
    <link rel="stylesheet" href="{% static 'cv/css/magnific-popup.css'%}">

   <!-- Script
   ================================================== -->
	<script src="{% static 'cv/js/modernizr.js' %}"></script>

   <!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="favicon.png" >

</head>

<body>

   <!-- Header
   ================================================== -->
   <header id="home">

      <nav id="nav-wrap">

         <a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show navigation</a>
	      <a class="mobile-btn" href="#" title="Hide navigation">Hide navigation</a>

         <ul id="nav" class="nav">
            <li class="current"><a class="smoothscroll" href="#home">Home</a></li>
            <li><a class="smoothscroll" href="#about">About</a></li>
	         <li><a class="smoothscroll" href="#resume">Resume</a></li>
            <li><a class="smoothscroll" href="#portfolio">Portfolio</a></li>
         </ul> <!-- end #nav -->

      </nav> <!-- end #nav-wrap -->

      <div class="row banner ">
         <div class="banner-text">
            <h1 class="responsive-headline">I'm Po-Wen Kao</h1>
             <div class="row">
                 <h3> Software Engineering · Robotics · IT</h3>
             </div>
            <ul class="social">
               <li><a href="https://www.linkedin.com/in/powen-kao/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
               <li><a href="https://gitlab.com/hp5588" target="_blank"><i class="fa fa-gitlab"></i></a></li>
               <li><a href="https://github.com/hp5588" target="_blank"><i class="fa fa-github"></i></a></li>
            </ul>
         </div>
      </div>

   </header> <!-- Header End -->


   <!-- Docker Section
   ================================================== -->
   <section id="docker">
       <div class="row">
           <div class="twelve columns">
               <h3 class="no-margin">Site is deployed from my <a href="https://hub.docker.com/r/hp5588/cv-kao" target="_blank">Docker Hub</a> image using GCP VM</h3>
           </div>
       </div>
   </section>

   <!-- About Section
   ================================================== -->
   <section id="about">

      <div class="row">

         <div class="three columns no-padding">

            <img class="profile-pic"  src="{% static 'cv/images/profilepic.jpg' %}" alt="" />

         </div>

         <div class="nine columns main-col">

            <h2>About Me</h2>

            <p> Enjoy exploring the latest technology and gaining hands-on experience, I consistently dedicate myself to building hobby projects in the embedded application including IoT and apps on iOS/Android.
                Knowing deep in mind that I am fascinated by the beauty of embedded systems, I further joined the master program in Uni Freiburg in 2018.
                Later in 2019, I found an internship opportunity in the UI Advanced Engineering department at Daimler that prototypes on the latest UI concept.
                Working closely with graphic designers, we bring the design to live.
                More recently, I am working on a master thesis in the same department while looking forward to the next adventure.
                The ideal position would be an engineer that has the potential to shape the future.
                Bringing concepts to prototype and finally empower the world with the production-grade products.
            </p>

            <div class="row">

               <div class="columns contact-details">

                  <h2>Contact Details</h2>
                  <p class="address">
						   <span>Po-Wen Kao</span><br>
						   <span>Stuttgart,<br>
						         Germany
                            </span><br>
                     <span>powen.kao.tw@gmail.com</span>
					   </p>

               </div>

{#               <div class="columns download">#}
{#                  <p>#}
{#                     <a href="#" class="button"><i class="fa fa-download"></i>Download Resume</a>#}
{#                  </p>#}
{#               </div>#}

            </div> <!-- end row -->

         </div> <!-- end .main-col -->

      </div>

   </section> <!-- About Section End-->


   <!-- Resume Section
   ================================================== -->
   <section id="resume">

      <!-- Education
      ----------------------------------------------- -->
      <div class="row education">

         <div class="three columns header-col">
            <h1><span>Education</span></h1>
         </div>

         <div class="nine columns main-col">

             {% if education_list %}
                 {% for education in education_list %}
                     <div class="row item">
                           <div class="twelve columns">
                              <h3>{{ education.university }}<span class="info"> - {{education.country}}</span></h3>
                              <p class="info">{{ education.major }} <span>&bull;</span> <em class="date">{{ education.start_date|date:"M Y" }} - {{ education.end_date|date:"M Y" }}</em></p>
                               <pre>{{ education.description|safe }}
                               </pre>
                           </div>
                    </div> <!-- item end -->
                 {% endfor %}
             {% endif %}



         </div> <!-- main-col end -->

      </div> <!-- End Education -->


      <!-- Experience
      ----------------------------------------------- -->
      <div class="row experience">

         <div class="three columns header-col">
            <h1><span>Experience</span></h1>
         </div>

         <div class="nine columns main-col">
             {% if experience_list %}
                 {% for experience in experience_list %}
                     <div class="row item">
                       <div class="twelve columns">
                          <h3>{{experience.title}} <span class="info"> - {{experience.department}}</span></h3>
                          <p class="info">{{ experience.position }} <span>&bull;</span>
                              <em class="date">{{ experience.start_date|date:"M Y" }} - {{ experience.end_date|date:"M Y" }}</em>
                          </p>
                          <pre>{{experience.description|safe}}
                          </pre>

                       </div>
                     </div>
                 {% endfor %}
            {% endif %}

         </div> <!-- main-col end -->

      </div> <!-- End Work -->


      <!-- Skills
      ----------------------------------------------- -->
      <div class="row skill" id="skills">

         <div class="three columns header-col">
            <h1><span>Skills</span></h1>
         </div>

         <div class="nine columns main-col">

            <p>Familiar with programming language from low-level C to object oriented language such as C++, Python and Java. Wide range of experience in various tools and frameworks.</p>
            {% regroup skill_list by get_category as category_list %}
            {% for category, skill_list in category_list %}
                <h3><span> {{ category.name }}</span></h3>
                <table class="skill-category" style="width: 100%; text-align: left">
                    {% if not category.collapse %}
                         {% for skill in skill_list|dictsortreversed:"level" %}
                            <tr>
                                <th style="width: 20%; text-align: right">
                                    <h4>{{ skill.name }} </h4>
                                </th>
                                <th >
                                    <a>{{ skill.framework_set.all|dictsort:"name"|join:" | "  }}</a>
                                </th>
                            </tr>
                       {% endfor %}
                    {% else %}
                        <tr>
                            {% for skill in skill_list|dictsortreversed:"level" %}
                                    <th style="width: 20%; text-align: right">
                                        <h4>{{ skill.name }} </h4>
                                    </th>
                           {% endfor %}
                        </tr>
                    {% endif %}
                </table>
            {% endfor %}


         </div> <!-- main-col end -->

      </div> <!-- End skills -->

   </section> <!-- Resume Section End-->


   <!-- Portfolio Section
   ================================================== -->
   <section id="portfolio">

      <div class="row">
          <div class="three columns header-col">
              <h1><span>Portfolio</span></h1>
          </div>
          <div class="nine columns main-col">
              {% for port in portfolio_list %}
                  <div class="row portfolio-row">
                      <div class="twelve columns">
                          <a href="{{ port.link }}" style="display: block"></a>
                          <h2> {{ port.name }}</h2>
                          <div class="four columns header-col">
                              <img src="{{ port.image.url }}">
                          </div>
                          <div class="eight columns main-col">
                              <pre>{{port.description|safe}}</pre>
                          </div>
                      </div>
                        {% if port.tag_set.count > 0 %}
                          <div class="twelve columns tag-container">
                              <div class="tag tag-header"> <h4>Tags</h4></div>
                              {% for tag in port.tag_set.all|dictsort:"framework.name" %}
                                  <div class="tag">
                                      <a>#{{ tag.framework.full_name }}</a>
                                  </div>
                              {% endfor %}
                          </div>
                        {% endif %}

                      <div class="twelve columns portfolio-source-link">
                          <a href="{{ port.link }}" target="_blank" style="display: block">Source Code</a>
                      </div>
                  </div>
              {% endfor %}

              <div class="row collapsed portfolio-row">
                  <h3>Check Out other works on my <a href="https://gitlab.com/hp5588">Gitlab</a>.</h3>
              </div> <!-- twelve columns end -->
          </div>
      </div> <!-- row End -->

   </section> <!-- Portfolio Section End-->


   <!-- footer
   ================================================== -->
   <footer>

      <div class="row">

         <div class="twelve columns">

            <ul class="social-links">
               <li><a href="https://www.linkedin.com/in/powen-kao/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
               <li><a href="https://gitlab.com/hp5588" target="_blank"><i class="fa fa-gitlab"></i></a></li>
            </ul>

            <ul class="copyright">
               <li>&copy; Copyright {% now 'Y' %} Po-Wen Kao</li>
               <li>Derived from <a href="http://www.styleshout.com/" title="Styleshout" target="_blank">Styleshout</a></li>
            </ul>

         </div>

         <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#home"><i class="icon-up-open"></i></a></div>

      </div>

   </footer> <!-- Footer End-->

   <!-- Java Script
   ================================================== -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="{% static 'cv/js/jquery-1.10.2.min.js' %}"><\/script>')</script>
   <script type="text/javascript" src="{% static 'cv/js/jquery-migrate-1.2.1.min.js' %}"></script>

   <script src="{% static 'cv/js/jquery.flexslider.js' %}"></script>
   <script src="{% static 'cv/js/waypoints.js' %}"></script>
   <script src="{% static 'cv/js/jquery.fittext.js' %}"></script>
   <script src="{% static 'cv/js/magnific-popup.js' %}"></script>
   <script src="{% static 'cv/js/init.js' %}"></script>

</body>

</html>